name: Feature Request
description: Suggest a new idea or functional addition.
labels: ["feature"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      placeholder: Is your feature request related to a problem? Please describe.
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      placeholder: Describe the solution you would like to see.
    validations:
      required: true